/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Pessoa;

import DAO.PessoaDAO;
import Model.Caixa;
import Model.Pessoa;
import View.TelaPrincipalView;
import java.util.Comparator;

/**
 *
 * @author Gabriela
 */
public class PessoaListView extends javax.swing.JFrame {
    
    private PessoaDAO pessoaDAO = new PessoaDAO();
    
    public PessoaListView() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btListar = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        taListar = new javax.swing.JTextArea();
        btLimparTela = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btListar.setActionCommand("Listar Pessoas por Ordem Alfabética");
        btListar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btListar.setLabel("Listar Pessoas por Ordem Alfabética");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarlistarPessoas(evt);
            }
        });

        taListar.setColumns(20);
        taListar.setRows(5);
        jScrollPane2.setViewportView(taListar);

        btLimparTela.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btLimparTela.setLabel("LimparTela");
        btLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparTelalimparTela(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimparTela, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimparTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btListarlistarPessoas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarlistarPessoas
        pessoaDAO.recuperarTodasPessoas().sort(new Comparator<Pessoa>() {
            @Override
            public int compare(Pessoa p1, Pessoa p2) {
                return p1.getNome().compareTo(p2.getNome());
            }
        });

        for(Pessoa p : pessoaDAO.recuperarTodasPessoas()) {
            taListar.append(p.toString() + "\n");
        }
    }//GEN-LAST:event_btListarlistarPessoas

    private void btLimparTelalimparTela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparTelalimparTela
        taListar.setText("");
    }//GEN-LAST:event_btLimparTelalimparTela

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btLimparTela;
    private java.awt.Button btListar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taListar;
    // End of variables declaration//GEN-END:variables
}
